### ISSUE TITLE
Join forces with SVG.NET?

### ISSUE THREAD

**Issue by tebjan** [mono/SkiaSharp.Extended#87]
Hello,

we from SVG.NET currently consider splitting SVG processing from drawing. See: https://github.com/vvvv/SVG/issues/590 and https://github.com/vvvv/SVG/issues/607

It would make quite a lot of sense to switch the rendering part to Skia. We also have a lot of rendering code that could probably changed from System.Drawing to Skia. So that might have to be evaluated.

We also have a nice test framework/application that works on pixel comparison. If anyone is willing to work together on that, let us know.

**Comment by mattleibow** [comment]
This work is happening, and it looks very good so far: https://github.com/wieslawsoltes/Svg.Skia

To be really honest, I don't think our SkiaSharp.Svg is going to go anywhere. FFImageLoading has already moved on from this code. Our SVG codebase to not going to work in the real world because it wasn't designed to handle the way SVG is designed. 

On my side, I don't think I will be getting time to do much (if any) work on SVG, so I would rather talk to @wieslawsoltes on this work. I will try to contribute if I can, but at this point I would say the SVG is more a community project.

Google says they are going to be adding SVG, but it has been years and it is a lot of work. And, if we do this right, then SkiaSharp is just one of many backends - which is preferable in the long run.

**Comment by tebjan** [comment]
Ha, wasn't aware of this. I already saw him contributing to our repository. We'll figure it out. Thanks a lot for the input!

**Comment by mattleibow** [comment]
Thanks for this issue, but due the the fact that this library is now deprecated, no further work will be done on this library.
I would recommend using the far superior https://github.com/wieslawsoltes/Svg.Skia
